#!/bin/bash -e

emcc main.cpp --std=c++17 -Os -o gcd.wasm -s WASM=1 -s SIDE_MODULE=1 -s EXPORTED_FUNCTIONS='["_calculate_gcd"]' -s ONLY_MY_CODE=1

#-s ONLY_MY_CODE=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0

# emcc main.cpp -o gcd.js --std=c++17 -s EXPORT_ALL=1

