#!/bin/bash -e

emcc main.cpp --std=c++17 -o rewrite_file.html -s EXPORTED_FUNCTIONS='["_process_bytes"]' -s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]' -s FORCE_FILESYSTEM=1

# emcc main.cpp -o gcd.js --std=c++17 -s EXPORT_ALL=1

